externalIp: <external ip>

influxdb:
  enabled: false
  adminPassword: "admin_password"
  userPassword: "user_password"
  readOnlyUserPassword: "read_only_user_password"

external_influxdb_v2:
  enabled: false
  url: "https://example.com:8086"
  token: "influxdb_rw_token"
  organization: "myorganization"
  bucket: "mybucket"

mqttServices:
  traffic:
    enabled: true
    measurementName: "traffic-work"
    topicPrefix: "Traffic/Work/"
    configuration:
      origin: "Frankfurt"
      destination: "Stuttgart"
      language: "en"
      apiKey: "<your Google Maps Web Service API key, see https://github.com/googlemaps/google-maps-services-js#api-keys>"

  internet:
    enabled: true
    measurementName: "home-internet"
    topicPrefix: "Home/Internet/"
    configuration:
      assignToGigabitNode: false # Requires a node in the cluster to be labeled with "network-bandwidth=gigabit"

  sonyBravia:
    enabled: false
    topicPrefix: "Home/TV/"
    configuration:
      tvIp: "<TV IP>"

  airQuality:
    enabled: false
    measurementName: "home-air-quality"
    topicPrefix: "Home/Air/"

  bluetooth:
    enabled: false
    measurementName: "home-bluetooth"
    topicPrefix: "Home/Bluetooth/"

  motion:
    enabled: false
    measurementName: "home-motion"
    topicPrefix: "Home/Motion/"

http2mqtt:
  httpPort: 9001

grafana:
  enabled: false
  adminPassword: "admin_password"
