{{- if .Values.influxdb.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hercules.influxdb.fullname" . }}
  labels:
    {{- include "hercules.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: hercules-influxdb
      {{- include "hercules.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        app: hercules-influxdb
        {{- include "hercules.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: master
        image: influxdb:1.8
        ports:
        - containerPort: 8086
        env:
        - name: INFLUXDB_DB
          value: "herculesdb"
        - name: INFLUXDB_HTTP_AUTH_ENABLED
          value: "true"
        - name: INFLUXDB_ADMIN_USER
          value: "admin"
        - name: INFLUXDB_ADMIN_PASSWORD
          value: {{ .Values.influxdb.adminPassword | quote }}
        - name: INFLUXDB_USER
          value: "hercules"
        - name: INFLUXDB_USER_PASSWORD
          value: {{ .Values.influxdb.userPassword | quote }}
        - name: INFLUXDB_READ_USER
          value: "hercules_read_only"
        - name: INFLUXDB_READ_USER_PASSWORD
          value: {{ .Values.influxdb.readOnlyUserPassword | quote }}
{{- end }}
