---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hercules.http2mqtt.fullname" . }}
  labels:
    app: hercules-http2mqtt
    {{- include "hercules.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: {{ .Values.http2mqtt.httpPort }}
  selector:
    app: hercules-http2mqtt
    {{- include "hercules.selectorLabels" . | nindent 4 }}
  externalIPs:
    - {{ .Values.externalIp }}
