apiVersion: v1
kind: Service
metadata:
  name: {{ include "hercules.mosquitto.fullname" . }}
  labels:
    app: hercules-mosquitto
    {{- include "hercules.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 1883
  selector:
    app: hercules-mosquitto
    {{- include "hercules.selectorLabels" . | nindent 4 }}
  externalIPs:
    - {{ .Values.externalIp }}
