---
apiVersion: v1
kind: Service
metadata:
  name: hercules-mosquitto
  labels:
    app: hercules-mosquitto
    role: master
    tier: backend
spec:
  type: NodePort 
  ports:
  - protocol: TCP
    port: 1883
  selector:
    app: hercules-mosquitto
    role: master
    tier: backend
  externalIPs:
    - {{ .external_ip }}
